exports.schema = {
  _id: 'string',
  username: 'string',
  email: 'string',
  password: 'string',
  phones: ['string'],
  gender: 'string',
  birthdayDate: 'date',
  location: {
    name: 'string',
    placeId: 'string'
  },
  houseNumber: 'string',
  streetName: 'string',
  ranking: 'number|default:0',
  googleId: 'string|optional:true',
  googleAccessToken: 'string|optional:true',
  avatar: 'string|optional:true',
  emailVerified: 'boolean|default:false',
  description: {
    userDesc: 'string',
    companyDesc: 'string'
  },
  role: 'string',
  banned: 'boolean|default:false',
  banExpiration: 'date',
  resetPasswordToken: 'string',
  resetPasswordExpire: 'date|convert:true',
  activationToken: 'string',
  activationTokenExpire: 'date|convert:true',
  isDeleted: 'boolean|default:false',
  createdAt: 'date|convert:true',
  modifiedAt: 'date|convert:true|optional:true',
  lastLoginAt: 'date|convert:true|optional:true',
};

exports.fields = [
  '_id',
  'username',
  'description',
  'password',
  'phones',
  'email',
  'location',
  'houseNumber',
  'streetName',
  'ranking',
  'googleId',
  'resetPasswordToken',
  'resetPasswordExpire',
  'emailVerified',
  'role',
  'banned',
  'banExpiration',
  'activationToken',
  'activationTokenExpire',
  'googleAccessToken',
  'avatar',
  'isDeleted',
  'createdAt',
  'modifiedAt',
  'lastLoginAt',
];
