exports.schema = {
  _id: 'string',
  title: 'string',
  description: 'string',
  count: 'number|default:0',
  minCount: 'number|default:0',
  maxCount: 'number|default:0',
  status: 'string',
  isBuy: 'boolean|default:false',
  isNew: 'boolean|default:false',
  isTax: 'boolean|default:false',
  isCertificate: 'boolean|default:false',
  city: {
    name: 'string',
    placeId: 'string'
  },
  houseNumber: 'string',
  streetName: 'string',
  price: 'number|default:0',
  customSize: 'string',
  customSort: 'string',
  customLoad: 'string',
  customPalletType: 'string',
  productBrands: ['string'],
  createdAt: 'date|convert:true',
  createdBy: 'string|optional:true',
  updatedAt: 'date|convert:true',
  updatedBy: 'string|optional:true',
  isDeleted: 'boolean|default:false',
  isActivated: 'boolean|default:false',
}

exports.fields = [
  '_id',
  'title',
  'description',
  'houseNumber',
  'streetName',
  'count',
  'minCount',
  'maxCount',
  'customSize',
  'customSort',
  'customLoad',
  'customPalletType',
  'productBrands',
  'status',
  'isBuy',
  'isNew',
  'isTax',
  'isCertificate',
  'city',
  'price',
  'createdAt',
  'createdBy',
  'updatedAt',
  'updatedBy',
  'isDeleted',
  'isActivated'
];
